### Numpy 넘파이

In [2]:
import random

In [6]:
import numpy

In [5]:
%pip install numpy

Collecting numpy
  Downloading numpy-2.4.3-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Downloading numpy-2.4.3-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB 640.0 kB/s eta 0:00:20
   ---------------------------------------- 0.1/12.6 MB 1.2 MB/s eta 0:00:11
   -- ------------------------------------- 0.7/12.6 MB 4.9 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/12.6 MB 7.3 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/12.6 MB 7.3 MB/s eta 0:00:02
   ----------- ---------------------------- 3.6/12.6 MB 12.6 MB/s eta 0:00:01
   ----------------- ---------------------- 5.4/12.6 MB 17.1 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.6 MB 23.3 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 22.6 MB/s eta 0:00:01
   ------------------------------------- -- 11.9/12.6 MB 50.4 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 43.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 38.4 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-2.4.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# !py -m pip install numpy 
# 위 다른게 설치가 안된다면 위 코드를 사용하면 된다

In [7]:
import numpy as np

print(np.__version__)

2.4.3

In [8]:
alist = [1,2,3,4,5,6,7]

In [9]:
print(type(alist))

<class 'list'>

In [10]:
alist

[1, 2, 3, 4, 5, 6, 7]

In [11]:
ar1 = np.array(alist)

In [13]:
print(type(ar1))
print(ar1)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]

In [14]:
ar1

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
ar1.dtype

dtype('int64')

In [16]:
list_data = [1,2.0,3]

ar2 = np.array(list_data)
print(ar2)
print(ar2.dtype)

[1. 2. 3.]
float64

In [17]:
ar1.ndim

1

In [18]:
ar1.shape

(7,)

In [20]:
ar3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [21]:
print(ar3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

In [22]:
print(ar3.ndim)

2

In [23]:
print(ar3.shape)

(3, 4)

In [30]:
ar4 = ar3.reshape(2, -1)

In [31]:
print(ar4)
print(ar4.ndim)
print(ar4.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2
(2, 6)

In [33]:
ar3.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
ar5 = ar3.reshape(3, -1, 2)

In [36]:
print(ar5)
print(ar5.ndim)
print(ar5.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
(3, 2, 2)

In [38]:
x = np.arange(1, 1001)
x

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  151,  152,  153,  154,
        155,  156,  157,  158,  159,  160,  161,  162,  163,  164,  165,
        166,  167,  168,  169,  170,  171,  172,  173,  174,  175,  176,
        177,  178,  179,  180,  181,  182,  183,  184,  185,  186,  187,
        188,  189,  190,  191,  192,  193,  194,  195,  196,  197,  198,
        199,  200,  201,  202,  203,  204,  205,  206,  207,  208,  209,
        210,  211,  212,  213,  214,  215,  216,  217,  218,  219,  220,
        221,  222,  223,  224,  225,  226,  227,  228,  229,  230,  231,
        232,  233,  234,  235,  236,  237,  238,  239,  240,  241,  242,
        243,  244,  245,  246,  247,  248,  249,  250,  251,  252,  253,
        254,  255,  256,  257,  258,  259,  260,  261,  262,  263,  264,
        265,  266,  267,  268,  269,  270,  271,  272,  273,  274,  275,
        276,  277,  278,  279,  280,  281,  282,  283,  284,  285,  286,
        287,  288,  289,  290,  291,  292,  293,  294,  295,  296,  297,
        298,  299,  300,  301,  302,  303,  304,  305,  306,  307,  308,
        309,  310,  311,  312,  313,  314,  315,  316,  317,  318,  319,
        320,  321,  322,  323,  324,  325,  326,  327,  328,  329,  330,
        331,  332,  333,  334,  335,  336,  337,  338,  339,  340,  341,
        342,  343,  344,  345,  346,  347,  348,  349,  350,  351,  352,
        353,  354,  355,  356,  357,  358,  359,  360,  361,  362,  363,
        364,  365,  366,  367,  368,  369,  370,  371,  372,  373,  374,
        375,  376,  377,  378,  379,  380,  381,  382,  383,  384,  385,
        386,  387,  388,  389,  390,  391,  392,  393,  394,  395,  396,
        397,  398,  399,  400,  401,  402,  403,  404,  405,  406,  407,
        408,  409,  410,  411,  412,  413,  414,  415,  416,  417,  418,
        419,  420,  421,  422,  423,  424,  425,  426,  427,  428,  429,
        430,  431,  432,  433,  434,  435,  436,  437,  438,  439,  440,
        441,  442,  443,  444,  445,  446,  447,  448,  449,  450,  451,
        452,  453,  454,  455,  456,  457,  458,  459,  460,  461,  462,
        463,  464,  465,  466,  467,  468,  469,  470,  471,  472,  473,
        474,  475,  476,  477,  478,  479,  480,  481,  482,  483,  484,
        485,  486,  487,  488,  489,  490,  491,  492,  493,  494,  495,
        496,  497,  498,  499,  500,  501,  502,  503,  504,  505,  506,
        507,  508,  509,  510,  511,  512,  513,  514,  515,  516,  517,
        518,  519,  520,  521,  522,  523,  524,  525,  526,  527,  528,
        529,  530,  531,  532,  533,  534,  535,  536,  537,  538,  539,
        540,  541,  542,  543,  544,  545,  546,  547,  548,  549,  550,
        551,  552,  553,  554,  555,  556,  557,  558,  559,  560,  561,
        562,  563,  564,  565,  566,  567,  568,  569,  570,  571,  572,
        573,  574,  575,  576,  577,  578,  579,  580,  581,  582,  583,
        584,  585,  586,  587,  588,  589,  590,  591,  592,  593,  594,
        595,  596,  597,  598,  599,  600,  601,  602,  603,  604,  605,
        606,  607,  608,  609,  610,  611,  612,  613,  614,  615,  616,
        617,  618,  619,  620,  621,  622,  623,  624,  625,  626,  627,
        628,  629,  630,  631,  632,  633,  634,  635,  636,  637,  638,
        639,  640,  641,  642,  643,  644,  645,  646,  647,  648,  649,
        650,  651,  652,  653,  654,  655,  656,  657,  658,  659,  660,
        661,  662,  663,  664,  665,  666,  667,  668,  669,  670,  671,
        672,  673,  674,  675,  676,  677,  678,  679,  680,  681,  682,
        683,  684,  685,  686,  687,  688,  689,  690,  691,  692,  693,
        694,  695,  696,  697,  698,  699,  700,  701,  702,  703,  704,
        705,  706,  707,  708,  709,  710,  711,  712,  713,  714,  715,
        716,  717,  718,  719,  720,  721,  722,  723,  724,  725,  726,
        727,  728,  729,  730,  731,  732,  733,  734,  735,  736,  737,
        738,  739,  740,  741,  742,  743,  744,  745,  746,  747,  748,
        749,  750,  751,  752,  753,  754,  755,  756,  757,  758,  759,
        760,  761,  762,  763,  764,  765,  766,  767,  768,  769,  770,
        771,  772,  773,  774,  775,  776,  777,  778,  779,  780,  781,
        782,  783,  784,  785,  786,  787,  788,  789,  790,  791,  792,
        793,  794,  795,  796,  797,  798,  799,  800,  801,  802,  803,
        804,  805,  806,  807,  808,  809,  810,  811,  812,  813,  814,
        815,  816,  817,  818,  819,  820,  821,  822,  823,  824,  825,
        826,  827,  828,  829,  830,  831,  832,  833,  834,  835,  836,
        837,  838,  839,  840,  841,  842,  843,  844,  845,  846,  847,
        848,  849,  850,  851,  852,  853,  854,  855,  856,  857,  858,
        859,  860,  861,  862,  863,  864,  865,  866,  867,  868,  869,
        870,  871,  872,  873,  874,  875,  876,  877,  878,  879,  880,
        881,  882,  883,  884,  885,  886,  887,  888,  889,  890,  891,
        892,  893,  894,  895,  896,  897,  898,  899,  900,  901,  902,
        903,  904,  905,  906,  907,  908,  909,  910,  911,  912,  913,
        914,  915,  916,  917,  918,  919,  920,  921,  922,  923,  924,
        925,  926,  927,  928,  929,  930,  931,  932,  933,  934,  935,
        936,  937,  938,  939,  940,  941,  942,  943,  944,  945,  946,
        947,  948,  949,  950,  951,  952,  953,  954,  955,  956,  957,
        958,  959,  960,  961,  962,  963,  964,  965,  966,  967,  968,
        969,  970,  971,  972,  973,  974,  975,  976,  977,  978,  979,
        980,  981,  982,  983,  984,  985,  986,  987,  988,  989,  990,
        991,  992,  993,  994,  995,  996,  997,  998,  999, 1000])

In [41]:
x = np.arange(1, 6)
y = np.arange(6, 11)

In [42]:
x+y

array([ 7,  9, 11, 13, 15])

In [43]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]

In [45]:
print(x+1)
print(x-1)
print(x*2)
print(x/2)

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]

In [44]:
alist = [1,2,3,4,5]
blist = [6,7,8,9,10]
alist + blist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [37]:
L = range(1000)
%timeit L2 = [i**2 for i in L]

62.4 μs ± 1.99 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [46]:
arr = np.arange(1000)
%timeit arr2 = arr ** 2

1.12 μs ± 13.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [48]:
x == 1

array([ True, False, False, False, False])

In [50]:
a=[[0,1,2],[3,4,5]]

In [54]:
# 0, 1, 5 인덱싱으로 뽑아 주세요

a[0][0], a[0][1], a[1][-1]

(0, 1, 5)

In [57]:
b = np.array([[0,1,2],[3,4,5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
print(b[0,0], b[0,1], b[-1,-1])

0 1 5

In [60]:
c = np.array([[0,1,2,3],[4,5,6,7]])
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
# [0,1,2],[1,5]

print(c[0,0], c[0,1],c[0,2], c[0,1],c[1,1])

0 1 2 1 5

In [67]:
# 인선미 강사 예시

print(c[0,:3], c[:,1])
print(c[:,:2])

[0 1 2] [1 5]
[[0 1]
 [4 5]]

In [66]:
print(c[:,0],c[:,1])

[0 4] [1 5]

In [ ]:
a= np.array([1,2,3])
b= np.array([10,20,30])

print(2*a+b)
print(a==2)
print(b>10)
print((a==2) & (b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]

In [ ]:
a= np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([False,False,True,False,True,False,True,False,True,False])
a[idx]

array([2, 4, 6, 8])

In [74]:
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
idx = np.array([a % 2 ==0])
a[idx]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [76]:
# 인선미 강사 예시
a[a%2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8])
a[idx]

array([0, 2, 4, 6, 8])

In [78]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,0,0,0,0,0,1,1,1,1,1,2,2,2,2,2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [96]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[:,0],a[:,3:3+1])

[1 5 9] [[ 4]
 [ 8]
 [12]]

In [99]:
# 인선미 강사 예시

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[:,[True, False, False, True]] # bool 방식
a[:, [0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [ ]:
# 인선미 강사 예시
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
## 도전

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(x[x % 3 == 0])
print(x[x % 4 ==1])
print(x[(x % 3 == 0) & (x%4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]

In [ ]:
# 인선미 강사 예시

x % 3 == 0
x % 4 ==1

### Pandas 판다스

In [114]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\el043\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\el043\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\el043\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/9.9 MB 1.7 MB/s eta 0:00:06
   - -------------------------------------- 0.4/9.9 MB 3.3 MB/s eta 0:00:03
   --- ------------------------------------ 0.9/9.9 MB 6.1 MB/s eta 0:00:02
   ----- ---------------------------------- 1.4/9.9 MB 7.3 MB/s eta 0:00:02
   -------- ------------------------------- 2.0/9.9 MB 8.2 MB/s eta 0:00:01
   ---------- ----------------------------- 2.6/9.9 MB 8.8 MB/s eta 0:00:01
   ----------- ---------------------------- 2.8/9.9 MB 8.5 MB/s eta 0:00:01
   ------------- -------------------------- 3.4/9.9 MB 8.6 MB/s eta 0:00:01
   ---------------- ----------------------- 4.0/9.9 MB 9.1 MB/s eta 0:00:01
   ------------------ --------------------- 4.5/9.9 MB 9.3 MB/s eta 0:00:01
   -------------------- ------------------- 5.0/9.9 MB 9.4 MB/s eta 0:00:01
   ---------------------- ----------------- 5.6/9.9 MB 9.9 MB/s eta 0:00:01
   ----------------------- ---------------- 5.9/9.9 MB 9.7 MB/s eta 0:00:01
   ------------------------- -------------- 6.4/9.9 MB 9.7 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.9 MB 9.2 MB/s eta 0:00:01
   --------------------------- ------------ 6.9/9.9 MB 9.2 MB/s eta 0:00:01
   ----------------------------- ---------- 7.4/9.9 MB 9.2 MB/s eta 0:00:01
   ------------------------------- -------- 7.7/9.9 MB 9.1 MB/s eta 0:00:01
   --------------------------------- ------ 8.3/9.9 MB 9.3 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 9.2 MB/s eta 0:00:01
   ------------------------------------ --- 9.0/9.9 MB 9.0 MB/s eta 0:00:01
   -------------------------------------- - 9.5/9.9 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 8.7 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
   ---------------------------------------- 0.0/348.5 kB ? eta -:--:--
   --------------------------------------- 348.5/348.5 kB 10.9 MB/s eta 0:00:00
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.1 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [116]:
import pandas as pd

#### 데이터 프레임 만들기

In [132]:
df = pd.read_csv('data/heroes.csv')
df

      이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [133]:
pd.options.display.float_format = '{:.0f}'.format

In [134]:
df

      이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [ ]:
df.head(5) # top 몇등

      이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [ ]:
df.tail(2) # 뒤에서 몇등

      이름  나이   직업   국적    키        재산
5   캡틴마블  25  파일럿   미국  170 340000000
6  블랙위도우  32  스파이  러시아  170  50000000

In [ ]:
df.sample(3) # 암거나 몇개

      이름  나이    직업     국적    키          재산
1     토르  45     신  아스가르드  190         NaN
0   아이언맨  58   CEO     미국  174 11500000000
2  스파이더맨  18  고등학생     미국  177         600

In [ ]:
df.info() # 정보

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      7 non-null      str
 1   나이      7 non-null      int64
 2   직업      7 non-null      str
 3   국적      7 non-null      str
 4   키       7 non-null      int64
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), str(3)
memory usage: 468.0 bytes

In [ ]:
df.describe() # 데이터의 분포도?

       나이   키          재산
count   7   7           5
mean   34 190  2578000120
std    13  36  5003440739
min    18 170         600
25%    26 172    50000000
50%    32 177   340000000
75%    39 184  1000000000
max    58 270 11500000000

In [140]:
df['국적'].unique()

<StringArray>
['미국', '아스가르드', '데미스키라', '러시아']
Length: 4, dtype: str

In [141]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [142]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [146]:
df.nlargest(5, '키')

      이름  나이     직업     국적    키          재산
4     헐크  33  핵물리학자     미국  270  1000000000
1     토르  45      신  아스가르드  190         NaN
3   원더우먼  27     공주  데미스키라  178         NaN
2  스파이더맨  18   고등학생     미국  177         600
0   아이언맨  58    CEO     미국  174 11500000000

In [147]:
type(df['나이'])

pandas.Series

In [148]:
type(df[['나이', '키']])

pandas.DataFrame

In [149]:
type(df)

pandas.DataFrame

In [150]:
df

      이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [154]:
df['이름'][:5]

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
Name: 이름, dtype: str

In [156]:
df.nlargest(2,'나이')

     이름  나이   직업     국적    키          재산
0  아이언맨  58  CEO     미국  174 11500000000
1    토르  45    신  아스가르드  190         NaN

In [157]:
# 인선미 강사 예시

df[:2]

     이름  나이   직업     국적    키          재산
0  아이언맨  58  CEO     미국  174 11500000000
1    토르  45    신  아스가르드  190         NaN

In [161]:
df[2]

KeyError: 2

In [166]:
df['나이'[:2]]

0    58
1    45
2    18
3    27
4    33
5    25
6    32
Name: 나이, dtype: int64

In [ ]:
loc, iloc

In [158]:
df.iloc[:2]

     이름  나이   직업     국적    키          재산
0  아이언맨  58  CEO     미국  174 11500000000
1    토르  45    신  아스가르드  190         NaN

In [168]:
df.iloc[[1,3,6]]

      이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [170]:
df.iloc[:5,:3]

      이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [175]:
df.iloc[2:5]

      이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000

In [ ]:
df.loc[행이름, 열이름]

In [171]:
df.loc[2]

이름    스파이더맨
나이       18
직업     고등학생
국적       미국
키       177
재산      600
Name: 2, dtype: object

In [174]:
df.loc[2:5]

      이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000

In [176]:
df.loc[3, '이름']

'원더우먼'

In [179]:
df.loc[:2, ['이름', '직업']]

      이름    직업
0   아이언맨   CEO
1     토르     신
2  스파이더맨  고등학생

In [180]:
df.loc[:2, '국적':'재산']

      국적    키          재산
0     미국  174 11500000000
1  아스가르드  190         NaN
2     미국  177         600

In [ ]:
# 내 생각
df.loc['나이'>=35]

TypeError: '>=' not supported between instances of 'str' and 'int'

In [189]:
# 인선미 강사 예시

df.loc[df['나이'] >= 35]

     이름  나이   직업     국적    키          재산
0  아이언맨  58  CEO     미국  174 11500000000
1    토르  45    신  아스가르드  190         NaN