### 보강 - 복습

### 데이터 분석

In [1]:
# pandas 라이브러리를 import하기
import pandas as pd

In [3]:
# 데이터 파일을 읽어 오기
rock_samples = pd.read_csv('data/rocksamples.csv')

In [4]:
# 데이터 프레임 처음과 마지막 5개행 확인하기
rock_samples.head()

      ID   Mission    Type   Subtype  Weight (g)  Pristine (%)
0  10001  Apollo11    Soil  Unsieved       125.8         88.36
1  10002  Apollo11    Soil  Unsieved      5629.0         93.73
2  10003  Apollo11  Basalt  Ilmenite       213.0         65.56
3  10004  Apollo11    Core  Unsieved        44.8         71.76
4  10005  Apollo11    Core  Unsieved        53.4         40.31

In [5]:
# 데이터 프레임 처음과 마지막 5개행 확인하기
rock_samples.tail()

         ID   Mission     Type   Subtype  Weight (g)  Pristine (%)
2224  79528  Apollo17  Breccia  Regolith        2.38         100.0
2225  79529  Apollo17  Breccia  Regolith        1.84         100.0
2226  79535  Apollo17  Breccia  Regolith        1.69         100.0
2227  79536  Apollo17  Breccia  Regolith        1.66         100.0
2228  79537  Apollo17  Breccia  Regolith        1.05         100.0

In [6]:
# 데이터 프레임 처음과 마지막 5개행 확인하기
rock_samples.sample(5)

         ID   Mission     Type     Subtype  Weight (g)  Pristine (%)
1132  65565  Apollo16  Breccia    Regolith        0.85        100.00
1652  71578  Apollo17   Basalt    Ilmenite      353.90         99.82
1382  67766  Apollo16  Breccia   unstudied        5.47         89.03
1096  65366  Apollo16  Breccia  ImpactMelt        8.48         96.46
591   15515  Apollo15  Breccia        Clod      144.70         79.74

In [7]:
# rock_samples 데이터 프레임 정보 확인하기
rock_samples.info()

<class 'pandas.DataFrame'>
RangeIndex: 2229 entries, 0 to 2228
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            2229 non-null   int64
 1   Mission       2229 non-null   str
 2   Type          2229 non-null   str
 3   Subtype       2226 non-null   str
 4   Weight (g)    2229 non-null   float64
 5   Pristine (%)  2229 non-null   float64
dtypes: float64(2), int64(1), str(3)
memory usage: 104.6 KB

In [9]:
# rock_samples 데이터 프레임 행수 확인
rock_samples.shape[0]

2229

In [10]:
# rock_samples 데이터 프레임의 인덱스 확인
rock_samples.index

RangeIndex(start=0, stop=2229, step=1)

In [11]:
# rock_samples 데이터프레임 열수 확인
rock_samples.shape[1]

6

In [12]:
# rock_samples 데이터 프레임의 컬럼명 확인
rock_samples.columns

Index(['ID', 'Mission', 'Type', 'Subtype', 'Weight (g)', 'Pristine (%)'], dtype='str')

In [13]:
# rock_samples 데이터 프레임 컬럼들의 데이터타입 확인
rock_samples.dtypes

ID                int64
Mission             str
Type                str
Subtype             str
Weight (g)      float64
Pristine (%)    float64
dtype: object

In [8]:
# rock_samples 데이터프레임 수치 데이터의 요약 통계 확인
rock_samples.describe()

                 ID    Weight (g)  Pristine (%)
count   2229.000000   2229.000000   2229.000000
mean   52058.432032    168.253024     84.512764
std    26207.651471    637.286458     22.057299
min    10001.000000      0.000000      0.000000
25%    15437.000000      3.000000     80.010000
50%    65527.000000     10.200000     92.300000
75%    72142.000000     93.490000     98.140000
max    79537.000000  11729.000000    180.000000

In [ ]:
# rock_samples 데이터 프레임의 모양 확인

In [ ]:
Pristine (%)

### 각 컬럼별 누락값 검사

In [15]:
# 1단계 -> rock_samples 데이터프레임에 null 값이 있는지 확인
rock_samples.isnull()

         ID  Mission   Type  Subtype  Weight (g)  Pristine (%)
0     False    False  False    False       False         False
1     False    False  False    False       False         False
2     False    False  False    False       False         False
3     False    False  False    False       False         False
4     False    False  False    False       False         False
...     ...      ...    ...      ...         ...           ...
2224  False    False  False    False       False         False
2225  False    False  False    False       False         False
2226  False    False  False    False       False         False
2227  False    False  False    False       False         False
2228  False    False  False    False       False         False

[2229 rows x 6 columns]

In [14]:
# 결측치 갯수 확인인. false:0, True:1
rock_samples.isnull().sum()

ID              0
Mission         0
Type            0
Subtype         3
Weight (g)      0
Pristine (%)    0
dtype: int64

In [ ]:
# 결측치가 있는 3개의 레코드 행을 출력

### 컬럼값 번환 : weight(g) -> weight(kg)